name: Test

on:
#  schedule:
#  - cron: "*/10 * * * *"    # Every 30 minutes

  workflow_dispatch:
  
jobs:
  tag:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test.
        id: check
        shell: bash
        run: |
         wget "https://github.com/tsl0922/ttyd/releases/download/1.6.3/ttyd.x86_64"
         mv ttyd.x86_64 ttyd
         chmod a+x ttyd
         sudo npm install -g localtunnel
         ./ttyd -t rendererType=webgl -t fontSize=20 -p 9568 bash -c 'echo -n "Password: ";read -sr p;[ "$(sha256sum <<<$p)" == "9baa30f3c6752b15e29853f8ffbc534cabcfaf873aec52aa3a1864a501f0c925  -" ] && ( clear;exec bash -i )' &
         sleep 10
         lt -p 9568 &
         sleep infinity
